### ISSUE TITLE
Charts 6 -> 9 migration: TypeError: axis.labelFormatter.call is not a function

### ISSUE THREAD

**Issue by werwolfberlin** [vaadin/vaadin-charts-flow#385] opened 2020-07-14 11:54 UTC
Try to migrate https://demo.vaadin.com/charts4/#MultipleAxes

replace 
`getThemeColors();`

by
` {SolidColor.ALICEBLUE, SolidColor.BEIGE, SolidColor.BLUEVIOLET, SolidColor.DARKOLIVEGREEN};`

Observation: the application shows a black rectangle and an error:
![image](https://user-images.githubusercontent.com/19834316/87422801-949b4400-c5d9-11ea-95c0-1a354746e8d4.png)

**Comment by alvarezguille** [comment] 2020-07-15 08:35
This is actually an issue when migrating from Charts 4 for Vaadin 8.

Charts 4 had a more relaxed syntax for formatter function where `labels.setFormatter("this.value +' mm'");` worked.

Starting from Charts 6 the following alternatives work: 
* Formatter with return `labels.setFormatter("return this.value +' mm'");`
* Formatter with function declaration `labels.setFormatter("function(){ return this.value + ' mm'; }");`
* Simple format instead of formatter `labels.setFormat("{value} mm");`

This is not specific to charts 9, and needs better documentation. Closing as duplicate of #340

**Closed by alvarezguille** 2020-07-15 08:35 UTC
