### ISSUE TITLE
Charts does not redraw properly after LiveReload

### ISSUE THREAD

**Issue by johannesh2** [vaadin/vaadin-charts-flow#395] opened 2020-08-07 11:06 UTC
Having the code below and modifying anything so that LiveReload refreshes browser, draws a black rectangle instead of the chart changes. I need to refresh the browser manually to see the changes.
```
@Route
public class MainView extends VerticalLayout {

    public MainView() {
        Chart chart = new Chart(ChartType.ORGANIZATION);
        Configuration conf = chart.getConfiguration();
        conf.getChart().setInverted(true);
        conf.getChart().setHeight("500px");
        conf.getTooltip().setOutside(true);
        conf.setTitle("Acme organization chart");
        
        
        NodeSeries series = new NodeSeries();
        series.setName("Acme");
        Node acme = new Node("Acme");
        Node headOffice = new Node("Head Office");
        Node branchOffice = new Node("Branch Office");

        series.add(acme, headOffice);
        series.add(headOffice, branchOffice);
        conf.addSeries(series);
        
        chart.drawChart();
        add(chart);
    }

}
```

- Spring Boot skeleton on Vaadin 17.0.0.beta1
- JDK 11
- No hotswap agent, no JRebel.

**Comment by alvarezguille** [comment] 2020-08-18 18:31
Reproduced with 17.0.0.beta1 
Seems to be fixed by https://github.com/vaadin/flow/pull/8836
Can't reproduce when overriding vaadin version to 17.0-SNAPSHOT or flow-client version to 4.0-SNAPSHOT

**Comment by alvarezguille** [comment] 2020-09-24 08:18
This issue was fixed and can't be reproduced with stable version of Vaadin 17

**Closed by alvarezguille** 2020-09-24 08:18 UTC
Labels: Impact: Low, Severity: Major, bug
